export const fakeMovies = [
  {
    id: "1",
    title: "Game of Thrones",
    type: "tv",
    releaseYear: 2011,
    genres: ["Action", "Adventure", "Drama"],
    imdb: "9.1",
    description:
      "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.",
    image: "/assets/images/test.png",
  },
  {
    id: "2",
    title: "The Dark Knight",
    type: "movie",
    releaseYear: 2008,
    genres: ["Action", "Crime", "Drama"],
    imdb: "9.0",
    description:
      "Batman faces a criminal mastermind known as the Joker, who plunges Gotham City into chaos and forces the hero to confront his own limits.",
    image: "/assets/images/test2.png",
  },
  {
    id: "3",
    title: "Interstellar",
    type: "movie",
    releaseYear: 2014,
    genres: ["Adventure", "Drama", "Sci-Fi"],
    imdb: "8.7",
    description:
      "A former NASA pilot joins a mission through a mysterious wormhole in search of a new home for humanity as Earth becomes increasingly uninhabitable.",
    image: "/assets/images/test3.png",
  },
  {
    id: "4",
    title: "Inception",
    type: "movie",
    releaseYear: 2010,
    genres: ["Action", "Sci-Fi", "Thriller"],
    imdb: "8.8",
    description:
      "A skilled thief who steals secrets through dreams is given a seemingly impossible task: planting an idea inside someone's mind.",
    image: "/assets/images/test4.png",
  },
  {
    id: "5",
    title: "The Lord of the Rings: The Return of the King",
    type: "movie",
    releaseYear: 2003,
    genres: ["Adventure", "Drama", "Fantasy"],
    imdb: "9.0",
    description:
      "As the final battle for Middle-earth approaches, Frodo and Sam continue their dangerous journey toward Mount Doom to destroy the One Ring.",
    image: "/assets/images/test.png",
  },
  {
    id: "6",
    title: "Stranger Things",
    type: "tv",
    releaseYear: 2016,
    genres: ["Drama", "Fantasy", "Horror"],
    imdb: "8.6",
    description:
      "A group of friends uncover a series of supernatural mysteries after a young boy mysteriously disappears from their small town.",
    image: "/assets/images/test2.png",
  },
  {
    id: "7",
    title: "Breaking Bad",
    type: "tv",
    releaseYear: 2008,
    genres: ["Crime", "Drama", "Thriller"],
    imdb: "9.5",
    description:
      "A high-school chemistry teacher diagnosed with cancer turns to manufacturing illegal drugs in an attempt to secure his family's financial future.",
    image: "/assets/images/test3.png",
  },
  {
    id: "8",
    title: "The Matrix",
    type: "movie",
    releaseYear: 1999,
    genres: ["Action", "Sci-Fi"],
    imdb: "8.7",
    description:
      "A computer programmer discovers that the world he knows is an elaborate simulation and joins a rebellion against the machines controlling humanity.",
    image: "/assets/images/test4.png",
  },
  {
    id: "9",
    title: "Dune: Part Two",
    type: "movie",
    releaseYear: 2024,
    genres: ["Action", "Adventure", "Drama"],
    imdb: "8.5",
    description:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    image: "/assets/images/test.png",
  },
  {
    id: "10",
    title: "The Witcher",
    type: "tv",
    releaseYear: 2019,
    genres: ["Action", "Adventure", "Fantasy"],
    imdb: "8.0",
    description:
      "A mutated monster hunter travels across a dangerous continent where humans, monsters, and magical forces struggle for power.",
    image: "/assets/images/test.png",
  },
  {
    id: "11",
    title: "Avatar",
    type: "movie",
    releaseYear: 2009,
    genres: ["Action", "Adventure", "Fantasy"],
    imdb: "7.9",
    description:
      "A former Marine becomes part of an alien world through a genetically engineered body and finds himself caught between two civilizations.",
    image: "/assets/images/test.png",
  },
  {
    id: "12",
    title: "The Shawshank Redemption",
    type: "movie",
    releaseYear: 1994,
    genres: ["Drama"],
    imdb: "9.3",
    description:
      "A banker sentenced to life in prison forms an unlikely friendship with another inmate and quietly holds onto hope for a better future.",
    image: "/assets/images/test.png",
  },
  {
    id: "13",
    title: "Wednesday",
    type: "tv",
    releaseYear: 2022,
    genres: ["Comedy", "Crime", "Fantasy"],
    imdb: "8.0",
    description:
      "Wednesday Addams investigates a series of mysterious crimes while navigating life at a strange academy filled with supernatural students.",
    image: "/assets/images/test.png",
  },
  {
    id: "14",
    title: "Avengers: Endgame",
    type: "movie",
    releaseYear: 2019,
    genres: ["Action", "Adventure", "Sci-Fi"],
    imdb: "8.4",
    description:
      "The surviving Avengers attempt to undo the devastating events of their previous battle and bring back those they lost.",
    image: "/assets/images/test.png",
  },
  {
    id: "15",
    title: "The Silence of the Lambs",
    type: "movie",
    releaseYear: 1991,
    genres: ["Crime", "Drama", "Thriller"],
    imdb: "8.6",
    description:
      "A young FBI trainee seeks the help of an imprisoned and highly intelligent killer to catch another dangerous criminal.",
    image: "/assets/images/test.png",
  },
  {
    id: "16",
    title: "The Prestige",
    type: "movie",
    releaseYear: 2006,
    genres: ["Drama", "Mystery", "Sci-Fi"],
    imdb: "8.5",
    description:
      "Two rival magicians become obsessed with creating the ultimate illusion, pushing their rivalry into increasingly dangerous territory.",
    image: "/assets/images/test.png",
  },
  {
    id: "17",
    title: "Arcane",
    type: "tv",
    releaseYear: 2021,
    genres: ["Animation", "Action", "Fantasy"],
    imdb: "9.0",
    description:
      "Two sisters find themselves on opposing sides of a growing conflict between the wealthy city of Piltover and the underground world of Zaun.",
    image: "/assets/images/test.png",
  },
  {
    id: "18",
    title: "Parasite",
    type: "movie",
    releaseYear: 2019,
    genres: ["Drama", "Thriller"],
    imdb: "8.5",
    description:
      "A struggling family gradually becomes entangled with a wealthy household, leading to a series of unexpected and dangerous consequences.",
    image: "/assets/images/test.png",
  },
  {
    id: "19",
    title: "Spider-Man: Into the Spider-Verse",
    type: "movie",
    releaseYear: 2018,
    genres: ["Animation", "Action", "Adventure"],
    imdb: "8.4",
    description:
      "A teenager becomes Spider-Man and encounters alternate versions of the hero from different dimensions.",
    image: "/assets/images/test.png",
  },
  {
    id: "20",
    title: "Everything Everywhere All at Once",
    type: "movie",
    releaseYear: 2022,
    genres: ["Action", "Adventure", "Comedy"],
    imdb: "7.7",
    description:
      "An overwhelmed woman discovers that she can access the lives of alternate versions of herself across countless parallel universes.",
    image: "/assets/images/test.png",
  },
];
