import type { Metadata } from "next";
import { Space_Grotesk, Rubik } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/appSidebar/AppSidebar";
import AppNavbar from "@/components/layout/AppNavbar";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cineverse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${rubik.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-col bg-slate-950">
        <SidebarProvider className="flex">
          <AppSidebar />
          <main className="grow p-2">
            <AppNavbar />
            <div>{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
