import type { Metadata } from "next";
import { Playfair, Rubik } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/appSidebar/AppSidebar";
import AppNavbar from "@/components/layout/appNavbar/AppNavbar";
import "swiper/css";
import "swiper/css/navigation";

const playfair = Playfair({
  variable: "--font-play-fair",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cineverse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} ${rubik.variable} h-full antialiased dark`}
    >
      <body className="min-h-full bg-slate-950">
        <SidebarProvider>
          <AppSidebar />
          <main className="grow py-2 relative">
            <AppNavbar />
            <div>{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
